backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "artigos"
    label: "Artigos"
    folder: "conteudo/artigos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Data", name: "data", widget: "datetime" }
      - { label: "Imagem", name: "imagem", widget: "image" }
      - { label: "Palavras-chave", name: "keywords", widget: "list", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: "noticias"
    label: "Notícias"
    folder: "conteudo/noticias"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Data", name: "data", widget: "datetime" }
      - { label: "Imagem", name: "imagem", widget: "image" }
      - { label: "Palavras-chave", name: "keywords", widget: "list", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: "avaliacoes_anim"
    label: "Avaliações - Animação"
    folder: "conteudo/avaliacoes/anim"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Nota", name: "nota", widget: "number", min: 0, max: 10, step: 0.1 }
      - { label: "Tipo", name: "tipo", widget: "hidden", default: "anim" }
      - { label: "Data", name: "data", widget: "datetime" }
      - { label: "Imagem", name: "imagem", widget: "image" }
      - { label: "Palavras-chave", name: "keywords", widget: "list", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: "avaliacoes_filmes"
    label: "Avaliações - Filmes"
    folder: "conteudo/avaliacoes/movies"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Nota", name: "nota", widget: "number", min: 0, max: 10, step: 0.1 }
      - { label: "Tipo", name: "tipo", widget: "hidden", default: "filme" }
      - { label: "Data", name: "data", widget: "datetime" }
      - { label: "Imagem", name: "imagem", widget: "image" }
      - { label: "Palavras-chave", name: "keywords", widget: "list", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: "avaliacoes_series"
    label: "Avaliações - Séries"
    folder: "conteudo/avaliacoes/series"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Nota", name: "nota", widget: "number", min: 0, max: 10, step: 0.1 }
      - { label: "Tipo", name: "tipo", widget: "hidden", default: "serie" }
      - { label: "Data", name: "data", widget: "datetime" }
      - { label: "Imagem", name: "imagem", widget: "image" }
      - { label: "Palavras-chave", name: "keywords", widget: "list", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
